### ISSUE TITLE
Make code more maintainable

### ISSUE THREAD

**Issue by NobodyForNothing** [NobodyForNothing/blood-pressure-monitor-fl#165]
There are multiple issues with the current code that lead to mistakes when adding new features:
- [x] classes are all over the place and should be limited to one public class per file
- [x] source code files are in general purpose folders with inconsistent naming scheme (#242)
- [X] there is logic in the UI code that makes it hard to test (#242)
- [X] many classes are just wrappers for functions and require way more arguments than necessary for calling a single function, especially the export code should be split into smaller parts and only take the arguments it uses (#248)
- [X] procedures for modifying and expanding code are poorly documented and unintuitive
- [x] #164

Tasks:
- [x] migrate singletons to the provider system
